Repository tonydoesathing/quickcheck-backend, pull requests merged in 2022-12, with the labels that each got.

#10 Implement students endpoint
  .gitignore
  README.md
  manage.py
  quickcheck/__init__.py
  quickcheck/__pycache__/__init__.cpython-39.pyc
  quickcheck/__pycache__/settings.cpython-39.pyc
  quickcheck/__pycache__/urls.cpython-39.pyc
  quickcheck/__pycache__/wsgi.cpython-39.pyc
  quickcheck/asgi.py
  quickcheck/settings.py
  quickcheck/urls.py
  quickcheck/wsgi.py
  requirements.txt
  students/__init__.py
  students/__pycache__/__init__.cpython-39.pyc
  students/__pycache__/admin.cpython-39.pyc
  students/__pycache__/apps.cpython-39.pyc
  students/__pycache__/models.cpython-39.pyc
  students/__pycache__/serializers.cpython-39.pyc
  students/__pycache__/urls.cpython-39.pyc
  students/__pycache__/views.cpython-39.pyc
  students/admin.py
  students/apps.py
  students/migrations/0001_initial.py
  students/migrations/__init__.py
  students/migrations/__pycache__/0001_initial.cpython-39.pyc
  students/migrations/__pycache__/__init__.cpython-39.pyc
  students/models.py
  students/serializers.py
  students/tests.py
  students/urls.py
  students/views.py
Labels: enhancement

#14 Added UML export support
  .gitignore
  README.md
  quickcheck/settings.py
  requirements.txt
Labels: documentation

#15 Connect models
  apis/__init__.py
  apis/admin.py
  apis/apps.py
  apis/migrations/0001_initial.py
  apis/migrations/__init__.py
  apis/models.py
  apis/serializers.py
  apis/tests.py
  apis/urls.py
  apis/views.py
  quickcheck/__pycache__/settings.cpython-39.pyc
  quickcheck/__pycache__/urls.cpython-39.pyc
  quickcheck/settings.py
  quickcheck/urls.py
  students/__pycache__/__init__.cpython-39.pyc
  students/__pycache__/admin.cpython-39.pyc
  students/__pycache__/apps.cpython-39.pyc
  students/__pycache__/models.cpython-39.pyc
  students/__pycache__/serializers.cpython-39.pyc
  students/__pycache__/urls.cpython-39.pyc
  students/__pycache__/views.cpython-39.pyc
  students/admin.py
  students/migrations/0001_initial.py
  students/migrations/__pycache__/0001_initial.cpython-39.pyc
  students/migrations/__pycache__/__init__.cpython-39.pyc
  students/models.py
  students/serializers.py
  students/urls.py
  students/views.py
Labels: enhancement

#18 Reformat get assessments return value
  apis/serializers.py
Labels: enhancement

#20 Development
  .gitignore
  README.md
  apis/__init__.py
  apis/admin.py
  apis/apps.py
  apis/migrations/0001_initial.py
  apis/migrations/__init__.py
  apis/models.py
  apis/serializers.py
  apis/tests.py
  apis/urls.py
  apis/views.py
  manage.py
  quickcheck/__init__.py
  quickcheck/__pycache__/__init__.cpython-39.pyc
  quickcheck/__pycache__/settings.cpython-39.pyc
  quickcheck/__pycache__/urls.cpython-39.pyc
  quickcheck/__pycache__/wsgi.cpython-39.pyc
  quickcheck/asgi.py
  quickcheck/settings.py
  quickcheck/urls.py
  quickcheck/wsgi.py
  requirements.txt
Labels: enhancement

#21 Added date_created and date_edited to models
  apis/migrations/0001_initial.py
  apis/models.py
  apis/serializers.py
  quickcheck/__pycache__/settings.cpython-39.pyc
Labels: enhancement

#24 Fixed bug
  apis/serializers.py
Labels: bug

#25 Return more data from post and put for assessments and groups
  apis/views.py
Labels: bug

#30 Add class data structure
  apis/migrations/0001_initial.py
  apis/migrations/0002_rename_student_class_assessment_class_id_and_more.py
  apis/models.py
  apis/serializers.py
  apis/urls.py
  apis/views.py
  quickcheck.postman_collection.json
  quickcheck/__pycache__/__init__.cpython-39.pyc
  quickcheck/__pycache__/settings.cpython-39.pyc
  quickcheck/__pycache__/urls.cpython-39.pyc
  quickcheck/__pycache__/wsgi.cpython-39.pyc
Labels: enhancement

#31 Authentication and permissions
  README.md
  apis/custompermission.py
  apis/migrations/0001_initial.py
  apis/migrations/0002_rename_student_class_assessment_class_id_and_more.py
  apis/models.py
  apis/serializers.py
  apis/views.py
  auth/__init__.py
  auth/admin.py
  auth/apps.py
  auth/migrations/__init__.py
  auth/models.py
  auth/serializers.py
  auth/tests.py
  auth/urls.py
  auth/views.py
  quickcheck.postman_collection.json
  quickcheck/__pycache__/settings.cpython-39.pyc
  quickcheck/__pycache__/urls.cpython-39.pyc
  quickcheck/settings.py
  quickcheck/urls.py
Labels: enhancement

#34 v2.0.0
  README.md
  apis/custompermission.py
  apis/migrations/0001_initial.py
  apis/models.py
  apis/serializers.py
  apis/urls.py
  apis/views.py
  auth/__init__.py
  auth/admin.py
  auth/apps.py
  auth/migrations/__init__.py
  auth/models.py
  auth/serializers.py
  auth/tests.py
  auth/urls.py
  auth/views.py
  quickcheck.postman_collection.json
  quickcheck/__pycache__/__init__.cpython-39.pyc
  quickcheck/__pycache__/settings.cpython-39.pyc
  quickcheck/__pycache__/urls.cpython-39.pyc
  quickcheck/__pycache__/wsgi.cpython-39.pyc
  quickcheck/settings.py
  quickcheck/urls.py
Labels: bug, documentation, enhancement

#36 Enabled cors
  quickcheck/__pycache__/settings.cpython-39.pyc
  quickcheck/__pycache__/urls.cpython-39.pyc
  quickcheck/settings.py
  requirements.txt
Labels: enhancement

#37 Enabled score modification on assessment put
  apis/views.py
  quickcheck/__pycache__/settings.cpython-39.pyc
Labels: enhancement

#40 Fixed deployment settings
  quickcheck/__pycache__/__init__.cpython-39.pyc
  quickcheck/__pycache__/settings.cpython-39.pyc
  quickcheck/__pycache__/urls.cpython-39.pyc
  quickcheck/__pycache__/wsgi.cpython-39.pyc
  quickcheck/settings.py
Labels: enhancement

#33 Restricted group and class assignment
  apis/admin.py
  apis/views.py
Labels: enhancement

#42 v2.1.0
  apis/admin.py
  apis/views.py
  quickcheck/__pycache__/__init__.cpython-39.pyc
  quickcheck/__pycache__/settings.cpython-39.pyc
  quickcheck/__pycache__/urls.cpython-39.pyc
  quickcheck/__pycache__/wsgi.cpython-39.pyc
  quickcheck/settings.py
  requirements.txt
Labels: bug, enhancement
